### ISSUE TITLE
EOS Genesis Key Utility - General, Key, Entropy, Validator

### ISSUE THREAD

**Issue by crypto5000** [EOSIO/genesis#23]
Hello Sandwich (@dskvr). Thank you for putting this key-tool together. It works great. 

I have a few questions/comments:
a) General: Do you recommend using the generated keypair from the current version to register? Or do you recommend waiting for a non-"experimental" version of the tool in the future?
b) Key: There seems to be an exposed private eos key hardcoded in the index.html file (in the value attribute field). I just want to make sure you're not using this anywhere, because there are bad actors that scrape github for credentials.
c) Entropy: I never got the "Adding CPU Entropy" message. I'm assuming my computer had collected enough entropy and this message was skipped. Is this expected behavior?
d) Validator: what is the purpose of the validator? Are all generated keypairs by the tool valid? Is this feature just to check for copy-and-paste errors for keypairs outside the tool?

Thank you in advance for the reply answers.

**Comment by dskvr** [comment]
a) It's "experimental" only on the grounds that I haven't gotten approval to sign and release a binary. Key generation uses `eosjs-ecc` and generates valid keypairs.
b) That key was used for debugging validation, I'll remove it.
c) Yes, when generating a key the first time, the `eosjs-ecc` gathers CPU entropy. It only does it once. 
d) Because hundreds of people have asked for a way to "validate their EOS key pair." The generated key will always be valid, there are numerous checks to ensure this.
