### ISSUE TITLE
Oh dear Developer, Please help me.

### ISSUE THREAD

**Issue by jihee1223** [EOSIO/genesis#50]
This is the person who has left the message below.

There are coded in only two exceptions processing address in the Snap Shot Program. ( (0xd0a6e6c54dbc68db5db3a091b171a77407ff7ccf, 0x86fa049857e0209aa7d9e616f7eb3b3b78ecfdb0)

Could you please allow misdeposited address of Eos Evolution? Please, Please.
This is the only way to get Eos token (I've mistransmitted) back for me. Please help me. Please, Please.

I attach the photo of Snap Shot Program.
![kakaotalk_20180529_230649767](https://user-images.githubusercontent.com/39737784/40669559-2b60ac5a-63a2-11e8-9f21-91d98aecefc9.png)
![kakaotalk_20180529_230721165](https://user-images.githubusercontent.com/39737784/40669560-2b934d54-63a2-11e8-82c5-0c1ca5912f2b.png)

**Comment by azdream** [comment]
In my opinion. Claim to EVO ( https://www.evolutionos.com )

**Comment by dskvr** [comment]
Reclaimables only apple to contracts that we can objectively exclude from the snapshot. They are an objective exclusion because they are contracts that were deployed for the purpose of the distribution, and are not to be included in the snapshot. Once there's a subjective claim made, it creates an impossible situation filled with subjective claims. The sheer volume of requests this would likely result in opens an attack vector, as it would become difficult to verify and evaluate every situation as accurately as needed. 

I would suggest arbitration on an EOSIO network for this situation.
